### ISSUE TITLE
Add a game size

### ISSUE THREAD

**Issue by Arkhorse** [VojtaStruhar/steam-review-template#3]
Given games are getting bigger and bigger, it might be a good idea to add a game size to the thing. I made this as an example. You can use it if you want.
```
---{ Game Size }---
☐ Floppy Disk
☐ Old Fashioned
☐ Workable
☐ Big
☐ Will eat 10% of your 1TB hard drive
☐ You will want an entire hard drive to hold it
☐ You will need to invest in a black hole to hold all the data
```

**Comment by VojtaStruhar** [comment]
Haha, sure! I added it to the config file 😁 [commit](https://github.com/VojtaStruhar/steam-review-template/commit/5136cd813830247dcb403f89c44bde6ee3a856fa)

It's a _really_ old project though - the build doesn't work anymore 😮‍💨  

I'll put a pin to it and try to rebuild it someday.. or you can get it up and running and submit a PR, that would be awesome

**Comment by VojtaStruhar** [comment]
Game size added. Now that I've rewritten it and the code actually works you can see it on the new website!
