### ISSUE TITLE
Error in deployment

### ISSUE THREAD

**Issue by Gfdcvn** [VojtaStruhar/steam-review-template#4]
Hi. I am trying to deploy it using github pages. I get this error. What do I do?
![image](https://github.com/VojtaStruhar/steam-review-template/assets/67555850/28d5b3e8-e9e3-4865-9acd-b8a13cf72ab8)
Also, did I choose the correct stuff?
![image](https://github.com/VojtaStruhar/steam-review-template/assets/67555850/c0556853-741d-4932-8d1d-9a59b38cf791)

**Comment by VojtaStruhar** [comment]
Hi, I have no real experience with Github pages deployments. But from looking at the error I think you might have the build output set to a different folder. It's usually something like `/build` or `/dist`.

I'd love to help, but I'm really not sure here.

**Comment by VojtaStruhar** [comment]
Hi, I've scrapped the old `create-react-scripts` mess and rewritten it to Astro. All works well now :)

If you still have issues with deploying it yourself let me know

**Comment by Gfdcvn** [comment]
Then what did you use to deploy it?

**Comment by VojtaStruhar** [comment]
GitHub actions. I used some default astro template that GitHub gave me and modified it for pnpm. It's funny to host a static website with a CI workflow, but here we are.

You can see the config file here: https://github.com/VojtaStruhar/steam-review-template/blob/master/.github/workflows/astro.yml
