### ISSUE TITLE
'Good' selection not working

### ISSUE THREAD

**Issue by fricht** [VojtaStruhar/steam-review-template#9]
When i try to select any `Good` option from any category (except the first one, `Graphics`), it doesn't select the `Good` option from that category, but rather from the first category (`Graphics`).
Every `Good` Label is linked to the `Graphics` `Good` radio btn, instead of their corresponding btn.

(It might be not clear, it's hard to explain)

## 
- Linux 6.8.9-300.fc40.x86_64
- Fedora Linux 40 (Workstation Edition)
- Gnome 46 (Wayland)
- Mozilla Firefox 126.0

## Steps to reproduce
- Click `Beautiful` option (anything except `Good`) in `Graphics` category
- Click `Good` option (the label) in  `Gameplay` category
### actual result
The `Good` option is selected in the `Graphics` category
### expected result
`Good` option selected in `Gameplay` category

**Comment by Luftwaffle46** [comment]
This is happening with me but for "decent"

**Comment by Luftwaffle46** [comment]
Potential workaround: click the dot to select, not the text itself

**Comment by VojtaStruhar** [comment]
You are right, that's so weird. I'll look into it 🤔 It's probably some accessibility thing

**Comment by VojtaStruhar** [comment]
Should be all good now. Huge thanks for pointing this out!!!
